site_name: Elcodi Documentation

site_url: http://www.elcodi.io/
site_description: Elcodi documentation website

repo_url: https://github.com/elcodi/docs

docs_dir: docs
theme_dir: elcodi

markdown_extensions:
    - toc:
        permalink: " #"

copyright: Copyright © 2014/2015 <a href="http://www.elcodi.io">Elcodi</a>. All rights reserved.
